name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="OobeyaQA" 
          repo_name="symphony-cd"  
          event_type="trigger-workflow" 
          service=${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OobeyaQA/symphony-cd/actions/workflows/$workflow_id/dispatches \
            -d "{\"ref\": \"${{ github.event.pull_request.head.ref || github.ref }}\"}" \
            --fail-with-body
